// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.

/**
 * AppSettingModel
 * Auto-generated from Drizzle schema table "app_settings"
 */
export class AppSettingModel {
  private _aiHarnessEffort!: "low" | "medium" | "high" | "xhigh" | "max";
  private _aiModel!: string;
  private _aiProvider!: "anthropic_api" | "claude_code";
  private _aiSummaryEffort!: "low" | "medium" | "high" | "xhigh" | "max";
  private _anthropicApiKeyEncrypted!: string | null;
  private _createdAt!: Date;
  private _githubLogin!: string | null;
  private _githubTokenEncrypted!: string | null;
  private _id!: number;
  private _updatedAt!: Date;

  constructor(data?: Partial<Record<keyof AppSettingModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setAiHarnessEffort(value: "low" | "medium" | "high" | "xhigh" | "max"): void {
    this._aiHarnessEffort = value;
  }
  setAiModel(value: string): void {
    this._aiModel = value;
  }
  setAiProvider(value: "anthropic_api" | "claude_code"): void {
    this._aiProvider = value;
  }
  setAiSummaryEffort(value: "low" | "medium" | "high" | "xhigh" | "max"): void {
    this._aiSummaryEffort = value;
  }
  setAnthropicApiKeyEncrypted(value: string | null): void {
    this._anthropicApiKeyEncrypted = value;
  }
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setGithubLogin(value: string | null): void {
    this._githubLogin = value;
  }
  setGithubTokenEncrypted(value: string | null): void {
    this._githubTokenEncrypted = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setUpdatedAt(value: Date): void {
    this._updatedAt = value;
  }

  // ===== Getters =====
  get aiHarnessEffort(): "low" | "medium" | "high" | "xhigh" | "max" {
    return this._aiHarnessEffort;
  }
  get aiModel(): string {
    return this._aiModel;
  }
  get aiProvider(): "anthropic_api" | "claude_code" {
    return this._aiProvider;
  }
  get aiSummaryEffort(): "low" | "medium" | "high" | "xhigh" | "max" {
    return this._aiSummaryEffort;
  }
  get anthropicApiKeyEncrypted(): string | null {
    return this._anthropicApiKeyEncrypted;
  }
  get createdAt(): Date {
    return this._createdAt;
  }
  get githubLogin(): string | null {
    return this._githubLogin;
  }
  get githubTokenEncrypted(): string | null {
    return this._githubTokenEncrypted;
  }
  get id(): number {
    return this._id;
  }
  get updatedAt(): Date {
    return this._updatedAt;
  }
}
