// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.
import type { HarnessStateSpec } from "../types/harness-library";
import type { AiUsage, MockedModule } from "../types/visualization-pipeline";

/**
 * HarnessLibraryEntryModel
 * Auto-generated from Drizzle schema table "harness_library_entries"
 */
export class HarnessLibraryEntryModel {
  private _aiModel!: string | null;
  private _aiUsage!: AiUsage | null;
  private _costUsd!: number | null;
  private _createdAt!: Date;
  private _displayName!: string;
  private _exportName!: string;
  private _filePath!: string;
  private _framework!: "react_vite" | "angular";
  private _harnessSource!: string | null;
  private _id!: number;
  private _lastError!: string | null;
  private _lastFailedVisualizationId!: number | null;
  private _lastRenderedAt!: Date | null;
  private _mockedModules!: MockedModule[];
  private _notes!: string;
  private _origin!: "run" | "scan" | "repair" | "import";
  private _repositoryId!: number;
  private _revision!: number;
  private _selector!: string | null;
  private _sourceFingerprint!: string | null;
  private _stateAllowance!: number;
  private _stateCount!: number;
  private _states!: HarnessStateSpec[];
  private _status!: "ready" | "needs_update" | "off_default_branch";
  private _updatedAt!: Date;
  private _writtenAt!: Date | null;

  constructor(data?: Partial<Record<keyof HarnessLibraryEntryModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setAiModel(value: string | null): void {
    this._aiModel = value;
  }
  setAiUsage(value: AiUsage | null): void {
    this._aiUsage = value;
  }
  setCostUsd(value: number | null): void {
    this._costUsd = value;
  }
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setDisplayName(value: string): void {
    this._displayName = value;
  }
  setExportName(value: string): void {
    this._exportName = value;
  }
  setFilePath(value: string): void {
    this._filePath = value;
  }
  setFramework(value: "react_vite" | "angular"): void {
    this._framework = value;
  }
  setHarnessSource(value: string | null): void {
    this._harnessSource = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setLastError(value: string | null): void {
    this._lastError = value;
  }
  setLastFailedVisualizationId(value: number | null): void {
    this._lastFailedVisualizationId = value;
  }
  setLastRenderedAt(value: Date | null): void {
    this._lastRenderedAt = value;
  }
  setMockedModules(value: MockedModule[]): void {
    this._mockedModules = value;
  }
  setNotes(value: string): void {
    this._notes = value;
  }
  setOrigin(value: "run" | "scan" | "repair" | "import"): void {
    this._origin = value;
  }
  setRepositoryId(value: number): void {
    this._repositoryId = value;
  }
  setRevision(value: number): void {
    this._revision = value;
  }
  setSelector(value: string | null): void {
    this._selector = value;
  }
  setSourceFingerprint(value: string | null): void {
    this._sourceFingerprint = value;
  }
  setStateAllowance(value: number): void {
    this._stateAllowance = value;
  }
  setStateCount(value: number): void {
    this._stateCount = value;
  }
  setStates(value: HarnessStateSpec[]): void {
    this._states = value;
  }
  setStatus(value: "ready" | "needs_update" | "off_default_branch"): void {
    this._status = value;
  }
  setUpdatedAt(value: Date): void {
    this._updatedAt = value;
  }
  setWrittenAt(value: Date | null): void {
    this._writtenAt = value;
  }

  // ===== Getters =====
  get aiModel(): string | null {
    return this._aiModel;
  }
  get aiUsage(): AiUsage | null {
    return this._aiUsage;
  }
  get costUsd(): number | null {
    return this._costUsd;
  }
  get createdAt(): Date {
    return this._createdAt;
  }
  get displayName(): string {
    return this._displayName;
  }
  get exportName(): string {
    return this._exportName;
  }
  get filePath(): string {
    return this._filePath;
  }
  get framework(): "react_vite" | "angular" {
    return this._framework;
  }
  get harnessSource(): string | null {
    return this._harnessSource;
  }
  get id(): number {
    return this._id;
  }
  get lastError(): string | null {
    return this._lastError;
  }
  get lastFailedVisualizationId(): number | null {
    return this._lastFailedVisualizationId;
  }
  get lastRenderedAt(): Date | null {
    return this._lastRenderedAt;
  }
  get mockedModules(): MockedModule[] {
    return this._mockedModules;
  }
  get notes(): string {
    return this._notes;
  }
  get origin(): "run" | "scan" | "repair" | "import" {
    return this._origin;
  }
  get repositoryId(): number {
    return this._repositoryId;
  }
  get revision(): number {
    return this._revision;
  }
  get selector(): string | null {
    return this._selector;
  }
  get sourceFingerprint(): string | null {
    return this._sourceFingerprint;
  }
  get stateAllowance(): number {
    return this._stateAllowance;
  }
  get stateCount(): number {
    return this._stateCount;
  }
  get states(): HarnessStateSpec[] {
    return this._states;
  }
  get status(): "ready" | "needs_update" | "off_default_branch" {
    return this._status;
  }
  get updatedAt(): Date {
    return this._updatedAt;
  }
  get writtenAt(): Date | null {
    return this._writtenAt;
  }
}
