// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.

/**
 * HarnessLibraryJobEventModel
 * Auto-generated from Drizzle schema table "harness_library_job_events"
 */
export class HarnessLibraryJobEventModel {
  private _createdAt!: Date;
  private _id!: number;
  private _jobId!: number;
  private _level!: "info" | "warn" | "error";
  private _message!: string;

  constructor(data?: Partial<Record<keyof HarnessLibraryJobEventModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setJobId(value: number): void {
    this._jobId = value;
  }
  setLevel(value: "info" | "warn" | "error"): void {
    this._level = value;
  }
  setMessage(value: string): void {
    this._message = value;
  }

  // ===== Getters =====
  get createdAt(): Date {
    return this._createdAt;
  }
  get id(): number {
    return this._id;
  }
  get jobId(): number {
    return this._jobId;
  }
  get level(): "info" | "warn" | "error" {
    return this._level;
  }
  get message(): string {
    return this._message;
  }
}
