// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.
import type { AiUsage } from "../types/visualization-pipeline";

/**
 * HarnessLibraryJobModel
 * Auto-generated from Drizzle schema table "harness_library_jobs"
 */
export class HarnessLibraryJobModel {
  private _aiModel!: string;
  private _aiUsage!: AiUsage | null;
  private _completedAt!: Date | null;
  private _componentIds!: number[] | null;
  private _createdAt!: Date;
  private _currentLabel!: string | null;
  private _errorMessage!: string | null;
  private _failedCount!: number;
  private _id!: number;
  private _jobId!: string | null;
  private _kind!: "scan" | "rescan" | "repair";
  private _repositoryId!: number;
  private _scanSha!: string | null;
  private _skippedCount!: number;
  private _spendCapUsd!: number | null;
  private _spentUsd!: number;
  private _startedAt!: Date | null;
  private _stateAllowance!: number;
  private _status!: "queued" | "preparing" | "running" | "completed" | "cap_reached" | "failed" | "cancelled";
  private _totalCount!: number;
  private _updatedAt!: Date;
  private _visualizationId!: number | null;
  private _writtenCount!: number;

  constructor(data?: Partial<Record<keyof HarnessLibraryJobModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setAiModel(value: string): void {
    this._aiModel = value;
  }
  setAiUsage(value: AiUsage | null): void {
    this._aiUsage = value;
  }
  setCompletedAt(value: Date | null): void {
    this._completedAt = value;
  }
  setComponentIds(value: number[] | null): void {
    this._componentIds = value;
  }
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setCurrentLabel(value: string | null): void {
    this._currentLabel = value;
  }
  setErrorMessage(value: string | null): void {
    this._errorMessage = value;
  }
  setFailedCount(value: number): void {
    this._failedCount = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setJobId(value: string | null): void {
    this._jobId = value;
  }
  setKind(value: "scan" | "rescan" | "repair"): void {
    this._kind = value;
  }
  setRepositoryId(value: number): void {
    this._repositoryId = value;
  }
  setScanSha(value: string | null): void {
    this._scanSha = value;
  }
  setSkippedCount(value: number): void {
    this._skippedCount = value;
  }
  setSpendCapUsd(value: number | null): void {
    this._spendCapUsd = value;
  }
  setSpentUsd(value: number): void {
    this._spentUsd = value;
  }
  setStartedAt(value: Date | null): void {
    this._startedAt = value;
  }
  setStateAllowance(value: number): void {
    this._stateAllowance = value;
  }
  setStatus(value: "queued" | "preparing" | "running" | "completed" | "cap_reached" | "failed" | "cancelled"): void {
    this._status = value;
  }
  setTotalCount(value: number): void {
    this._totalCount = value;
  }
  setUpdatedAt(value: Date): void {
    this._updatedAt = value;
  }
  setVisualizationId(value: number | null): void {
    this._visualizationId = value;
  }
  setWrittenCount(value: number): void {
    this._writtenCount = value;
  }

  // ===== Getters =====
  get aiModel(): string {
    return this._aiModel;
  }
  get aiUsage(): AiUsage | null {
    return this._aiUsage;
  }
  get completedAt(): Date | null {
    return this._completedAt;
  }
  get componentIds(): number[] | null {
    return this._componentIds;
  }
  get createdAt(): Date {
    return this._createdAt;
  }
  get currentLabel(): string | null {
    return this._currentLabel;
  }
  get errorMessage(): string | null {
    return this._errorMessage;
  }
  get failedCount(): number {
    return this._failedCount;
  }
  get id(): number {
    return this._id;
  }
  get jobId(): string | null {
    return this._jobId;
  }
  get kind(): "scan" | "rescan" | "repair" {
    return this._kind;
  }
  get repositoryId(): number {
    return this._repositoryId;
  }
  get scanSha(): string | null {
    return this._scanSha;
  }
  get skippedCount(): number {
    return this._skippedCount;
  }
  get spendCapUsd(): number | null {
    return this._spendCapUsd;
  }
  get spentUsd(): number {
    return this._spentUsd;
  }
  get startedAt(): Date | null {
    return this._startedAt;
  }
  get stateAllowance(): number {
    return this._stateAllowance;
  }
  get status(): "queued" | "preparing" | "running" | "completed" | "cap_reached" | "failed" | "cancelled" {
    return this._status;
  }
  get totalCount(): number {
    return this._totalCount;
  }
  get updatedAt(): Date {
    return this._updatedAt;
  }
  get visualizationId(): number | null {
    return this._visualizationId;
  }
  get writtenCount(): number {
    return this._writtenCount;
  }
}
