// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.
import type { LiveHostState, LiveOpenRequestRecord } from "../types/harness-library";

/**
 * LiveSessionModel
 * Auto-generated from Drizzle schema table "live_sessions"
 */
export class LiveSessionModel {
  private _createdAt!: Date;
  private _errorMessage!: string | null;
  private _hosts!: LiveHostState[];
  private _id!: number;
  private _jobId!: string | null;
  private _lastActivityAt!: Date;
  private _lastHeartbeatAt!: Date;
  private _openRequests!: LiveOpenRequestRecord[];
  private _openRequestsVersion!: number;
  private _readyAt!: Date | null;
  private _status!: "starting" | "ready" | "stopping" | "stopped" | "failed";
  private _stoppedAt!: Date | null;
  private _stopReason!: "user" | "left" | "idle" | "max_duration" | "shutdown" | "error" | null;
  private _updatedAt!: Date;
  private _visualizationId!: number;

  constructor(data?: Partial<Record<keyof LiveSessionModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setErrorMessage(value: string | null): void {
    this._errorMessage = value;
  }
  setHosts(value: LiveHostState[]): void {
    this._hosts = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setJobId(value: string | null): void {
    this._jobId = value;
  }
  setLastActivityAt(value: Date): void {
    this._lastActivityAt = value;
  }
  setLastHeartbeatAt(value: Date): void {
    this._lastHeartbeatAt = value;
  }
  setOpenRequests(value: LiveOpenRequestRecord[]): void {
    this._openRequests = value;
  }
  setOpenRequestsVersion(value: number): void {
    this._openRequestsVersion = value;
  }
  setReadyAt(value: Date | null): void {
    this._readyAt = value;
  }
  setStatus(value: "starting" | "ready" | "stopping" | "stopped" | "failed"): void {
    this._status = value;
  }
  setStoppedAt(value: Date | null): void {
    this._stoppedAt = value;
  }
  setStopReason(value: "user" | "left" | "idle" | "max_duration" | "shutdown" | "error" | null): void {
    this._stopReason = value;
  }
  setUpdatedAt(value: Date): void {
    this._updatedAt = value;
  }
  setVisualizationId(value: number): void {
    this._visualizationId = value;
  }

  // ===== Getters =====
  get createdAt(): Date {
    return this._createdAt;
  }
  get errorMessage(): string | null {
    return this._errorMessage;
  }
  get hosts(): LiveHostState[] {
    return this._hosts;
  }
  get id(): number {
    return this._id;
  }
  get jobId(): string | null {
    return this._jobId;
  }
  get lastActivityAt(): Date {
    return this._lastActivityAt;
  }
  get lastHeartbeatAt(): Date {
    return this._lastHeartbeatAt;
  }
  get openRequests(): LiveOpenRequestRecord[] {
    return this._openRequests;
  }
  get openRequestsVersion(): number {
    return this._openRequestsVersion;
  }
  get readyAt(): Date | null {
    return this._readyAt;
  }
  get status(): "starting" | "ready" | "stopping" | "stopped" | "failed" {
    return this._status;
  }
  get stoppedAt(): Date | null {
    return this._stoppedAt;
  }
  get stopReason(): "user" | "left" | "idle" | "max_duration" | "shutdown" | "error" | null {
    return this._stopReason;
  }
  get updatedAt(): Date {
    return this._updatedAt;
  }
  get visualizationId(): number {
    return this._visualizationId;
  }
}
