// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.

/**
 * RepositoryModel
 * Auto-generated from Drizzle schema table "repositories"
 */
export class RepositoryModel {
  private _angularBuildConfiguration!: string | null;
  private _angularProject!: string | null;
  private _appRoot!: string;
  private _createdAt!: Date;
  private _defaultBranch!: string;
  private _entryFilePath!: string | null;
  private _framework!: "react_vite" | "angular";
  private _githubOwner!: string | null;
  private _githubRepo!: string | null;
  private _globalStylePaths!: string[];
  private _id!: number;
  private _isDeleted!: boolean;
  private _lastDetectedAt!: Date;
  private _localPath!: string;
  private _name!: string;
  private _packageManager!: "npm" | "pnpm" | "yarn";
  private _renderViewport!: "desktop" | "tablet" | "mobile";
  private _tsconfigPath!: string | null;
  private _updatedAt!: Date;
  private _viteConfigPath!: string | null;

  constructor(data?: Partial<Record<keyof RepositoryModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setAngularBuildConfiguration(value: string | null): void {
    this._angularBuildConfiguration = value;
  }
  setAngularProject(value: string | null): void {
    this._angularProject = value;
  }
  setAppRoot(value: string): void {
    this._appRoot = value;
  }
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setDefaultBranch(value: string): void {
    this._defaultBranch = value;
  }
  setEntryFilePath(value: string | null): void {
    this._entryFilePath = value;
  }
  setFramework(value: "react_vite" | "angular"): void {
    this._framework = value;
  }
  setGithubOwner(value: string | null): void {
    this._githubOwner = value;
  }
  setGithubRepo(value: string | null): void {
    this._githubRepo = value;
  }
  setGlobalStylePaths(value: string[]): void {
    this._globalStylePaths = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setIsDeleted(value: boolean): void {
    this._isDeleted = value;
  }
  setLastDetectedAt(value: Date): void {
    this._lastDetectedAt = value;
  }
  setLocalPath(value: string): void {
    this._localPath = value;
  }
  setName(value: string): void {
    this._name = value;
  }
  setPackageManager(value: "npm" | "pnpm" | "yarn"): void {
    this._packageManager = value;
  }
  setRenderViewport(value: "desktop" | "tablet" | "mobile"): void {
    this._renderViewport = value;
  }
  setTsconfigPath(value: string | null): void {
    this._tsconfigPath = value;
  }
  setUpdatedAt(value: Date): void {
    this._updatedAt = value;
  }
  setViteConfigPath(value: string | null): void {
    this._viteConfigPath = value;
  }

  // ===== Getters =====
  get angularBuildConfiguration(): string | null {
    return this._angularBuildConfiguration;
  }
  get angularProject(): string | null {
    return this._angularProject;
  }
  get appRoot(): string {
    return this._appRoot;
  }
  get createdAt(): Date {
    return this._createdAt;
  }
  get defaultBranch(): string {
    return this._defaultBranch;
  }
  get entryFilePath(): string | null {
    return this._entryFilePath;
  }
  get framework(): "react_vite" | "angular" {
    return this._framework;
  }
  get githubOwner(): string | null {
    return this._githubOwner;
  }
  get githubRepo(): string | null {
    return this._githubRepo;
  }
  get globalStylePaths(): string[] {
    return this._globalStylePaths;
  }
  get id(): number {
    return this._id;
  }
  get isDeleted(): boolean {
    return this._isDeleted;
  }
  get lastDetectedAt(): Date {
    return this._lastDetectedAt;
  }
  get localPath(): string {
    return this._localPath;
  }
  get name(): string {
    return this._name;
  }
  get packageManager(): "npm" | "pnpm" | "yarn" {
    return this._packageManager;
  }
  get renderViewport(): "desktop" | "tablet" | "mobile" {
    return this._renderViewport;
  }
  get tsconfigPath(): string | null {
    return this._tsconfigPath;
  }
  get updatedAt(): Date {
    return this._updatedAt;
  }
  get viteConfigPath(): string | null {
    return this._viteConfigPath;
  }
}
