// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.
import type { MockedModule, StructuralChange, SuccessorEvidence } from "../types/visualization-pipeline";

/**
 * VisualizationComponentModel
 * Auto-generated from Drizzle schema table "visualization_components"
 */
export class VisualizationComponentModel {
  private _aiNote!: string | null;
  private _baseDisplayName!: string | null;
  private _baseError!: string | null;
  private _baseExportName!: string | null;
  private _baseFilePath!: string | null;
  private _baseHarnessNotes!: string | null;
  private _baseHarnessSource!: string | null;
  private _baseImagePath!: string | null;
  private _baseMockedModules!: MockedModule[] | null;
  private _changeKind!: "modified" | "added" | "removed" | "affected_parent" | "replaced";
  private _changeReason!: string | null;
  private _codeDiff!: string | null;
  private _createdAt!: Date;
  private _diffImagePath!: string | null;
  private _diffPixelRatio!: number | null;
  private _displayName!: string;
  private _exportName!: string;
  private _filePath!: string;
  private _harnessNotes!: string | null;
  private _harnessSource!: string | null;
  private _headError!: string | null;
  private _headImagePath!: string | null;
  private _id!: number;
  private _imageHeight!: number | null;
  private _imageWidth!: number | null;
  private _mockedModules!: MockedModule[];
  private _rank!: number;
  private _renderStatus!: "pending" | "rendered" | "partial" | "failed" | "skipped";
  private _risk!: "none" | "check" | "likely_regression" | null;
  private _skipReason!: string | null;
  private _structuralDiff!: StructuralChange[] | null;
  private _successorEvidence!: SuccessorEvidence[] | null;
  private _updatedAt!: Date;
  private _visualChange!: "changed" | "unchanged" | "new" | "deleted" | null;
  private _visualizationId!: number;

  constructor(data?: Partial<Record<keyof VisualizationComponentModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setAiNote(value: string | null): void {
    this._aiNote = value;
  }
  setBaseDisplayName(value: string | null): void {
    this._baseDisplayName = value;
  }
  setBaseError(value: string | null): void {
    this._baseError = value;
  }
  setBaseExportName(value: string | null): void {
    this._baseExportName = value;
  }
  setBaseFilePath(value: string | null): void {
    this._baseFilePath = value;
  }
  setBaseHarnessNotes(value: string | null): void {
    this._baseHarnessNotes = value;
  }
  setBaseHarnessSource(value: string | null): void {
    this._baseHarnessSource = value;
  }
  setBaseImagePath(value: string | null): void {
    this._baseImagePath = value;
  }
  setBaseMockedModules(value: MockedModule[] | null): void {
    this._baseMockedModules = value;
  }
  setChangeKind(value: "modified" | "added" | "removed" | "affected_parent" | "replaced"): void {
    this._changeKind = value;
  }
  setChangeReason(value: string | null): void {
    this._changeReason = value;
  }
  setCodeDiff(value: string | null): void {
    this._codeDiff = value;
  }
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setDiffImagePath(value: string | null): void {
    this._diffImagePath = value;
  }
  setDiffPixelRatio(value: number | null): void {
    this._diffPixelRatio = value;
  }
  setDisplayName(value: string): void {
    this._displayName = value;
  }
  setExportName(value: string): void {
    this._exportName = value;
  }
  setFilePath(value: string): void {
    this._filePath = value;
  }
  setHarnessNotes(value: string | null): void {
    this._harnessNotes = value;
  }
  setHarnessSource(value: string | null): void {
    this._harnessSource = value;
  }
  setHeadError(value: string | null): void {
    this._headError = value;
  }
  setHeadImagePath(value: string | null): void {
    this._headImagePath = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setImageHeight(value: number | null): void {
    this._imageHeight = value;
  }
  setImageWidth(value: number | null): void {
    this._imageWidth = value;
  }
  setMockedModules(value: MockedModule[]): void {
    this._mockedModules = value;
  }
  setRank(value: number): void {
    this._rank = value;
  }
  setRenderStatus(value: "pending" | "rendered" | "partial" | "failed" | "skipped"): void {
    this._renderStatus = value;
  }
  setRisk(value: "none" | "check" | "likely_regression" | null): void {
    this._risk = value;
  }
  setSkipReason(value: string | null): void {
    this._skipReason = value;
  }
  setStructuralDiff(value: StructuralChange[] | null): void {
    this._structuralDiff = value;
  }
  setSuccessorEvidence(value: SuccessorEvidence[] | null): void {
    this._successorEvidence = value;
  }
  setUpdatedAt(value: Date): void {
    this._updatedAt = value;
  }
  setVisualChange(value: "changed" | "unchanged" | "new" | "deleted" | null): void {
    this._visualChange = value;
  }
  setVisualizationId(value: number): void {
    this._visualizationId = value;
  }

  // ===== Getters =====
  get aiNote(): string | null {
    return this._aiNote;
  }
  get baseDisplayName(): string | null {
    return this._baseDisplayName;
  }
  get baseError(): string | null {
    return this._baseError;
  }
  get baseExportName(): string | null {
    return this._baseExportName;
  }
  get baseFilePath(): string | null {
    return this._baseFilePath;
  }
  get baseHarnessNotes(): string | null {
    return this._baseHarnessNotes;
  }
  get baseHarnessSource(): string | null {
    return this._baseHarnessSource;
  }
  get baseImagePath(): string | null {
    return this._baseImagePath;
  }
  get baseMockedModules(): MockedModule[] | null {
    return this._baseMockedModules;
  }
  get changeKind(): "modified" | "added" | "removed" | "affected_parent" | "replaced" {
    return this._changeKind;
  }
  get changeReason(): string | null {
    return this._changeReason;
  }
  get codeDiff(): string | null {
    return this._codeDiff;
  }
  get createdAt(): Date {
    return this._createdAt;
  }
  get diffImagePath(): string | null {
    return this._diffImagePath;
  }
  get diffPixelRatio(): number | null {
    return this._diffPixelRatio;
  }
  get displayName(): string {
    return this._displayName;
  }
  get exportName(): string {
    return this._exportName;
  }
  get filePath(): string {
    return this._filePath;
  }
  get harnessNotes(): string | null {
    return this._harnessNotes;
  }
  get harnessSource(): string | null {
    return this._harnessSource;
  }
  get headError(): string | null {
    return this._headError;
  }
  get headImagePath(): string | null {
    return this._headImagePath;
  }
  get id(): number {
    return this._id;
  }
  get imageHeight(): number | null {
    return this._imageHeight;
  }
  get imageWidth(): number | null {
    return this._imageWidth;
  }
  get mockedModules(): MockedModule[] {
    return this._mockedModules;
  }
  get rank(): number {
    return this._rank;
  }
  get renderStatus(): "pending" | "rendered" | "partial" | "failed" | "skipped" {
    return this._renderStatus;
  }
  get risk(): "none" | "check" | "likely_regression" | null {
    return this._risk;
  }
  get skipReason(): string | null {
    return this._skipReason;
  }
  get structuralDiff(): StructuralChange[] | null {
    return this._structuralDiff;
  }
  get successorEvidence(): SuccessorEvidence[] | null {
    return this._successorEvidence;
  }
  get updatedAt(): Date {
    return this._updatedAt;
  }
  get visualChange(): "changed" | "unchanged" | "new" | "deleted" | null {
    return this._visualChange;
  }
  get visualizationId(): number {
    return this._visualizationId;
  }
}
