// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.
import type { HarnessStep } from "../types/harness-library";

/**
 * VisualizationComponentStateModel
 * Auto-generated from Drizzle schema table "visualization_component_states"
 */
export class VisualizationComponentStateModel {
  private _baseError!: string | null;
  private _baseFailureKind!:
    | "vite_unavailable"
    | "navigation"
    | "module_load"
    | "render_error"
    | "timeout"
    | "step_failed"
    | "browser"
    | "screenshot"
    | "file_missing"
    | "budget_exceeded"
    | "cancelled"
    | null;
  private _baseImagePath!: string | null;
  private _createdAt!: Date;
  private _diffImagePath!: string | null;
  private _diffPixelRatio!: number | null;
  private _headError!: string | null;
  private _headFailureKind!:
    | "vite_unavailable"
    | "navigation"
    | "module_load"
    | "render_error"
    | "timeout"
    | "step_failed"
    | "browser"
    | "screenshot"
    | "file_missing"
    | "budget_exceeded"
    | "cancelled"
    | null;
  private _headImagePath!: string | null;
  private _id!: number;
  private _imageHeight!: number | null;
  private _imageWidth!: number | null;
  private _onBase!: boolean;
  private _onHead!: boolean;
  private _ordinal!: number;
  private _renderStatus!: "pending" | "rendered" | "partial" | "failed" | "skipped";
  private _stateName!: string;
  private _steps!: HarnessStep[];
  private _updatedAt!: Date;
  private _visualChange!: "changed" | "unchanged" | "new" | "deleted" | null;
  private _visualizationComponentId!: number;
  private _visualizationId!: number;

  constructor(data?: Partial<Record<keyof VisualizationComponentStateModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setBaseError(value: string | null): void {
    this._baseError = value;
  }
  setBaseFailureKind(
    value:
      | "vite_unavailable"
      | "navigation"
      | "module_load"
      | "render_error"
      | "timeout"
      | "step_failed"
      | "browser"
      | "screenshot"
      | "file_missing"
      | "budget_exceeded"
      | "cancelled"
      | null
  ): void {
    this._baseFailureKind = value;
  }
  setBaseImagePath(value: string | null): void {
    this._baseImagePath = value;
  }
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setDiffImagePath(value: string | null): void {
    this._diffImagePath = value;
  }
  setDiffPixelRatio(value: number | null): void {
    this._diffPixelRatio = value;
  }
  setHeadError(value: string | null): void {
    this._headError = value;
  }
  setHeadFailureKind(
    value:
      | "vite_unavailable"
      | "navigation"
      | "module_load"
      | "render_error"
      | "timeout"
      | "step_failed"
      | "browser"
      | "screenshot"
      | "file_missing"
      | "budget_exceeded"
      | "cancelled"
      | null
  ): void {
    this._headFailureKind = value;
  }
  setHeadImagePath(value: string | null): void {
    this._headImagePath = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setImageHeight(value: number | null): void {
    this._imageHeight = value;
  }
  setImageWidth(value: number | null): void {
    this._imageWidth = value;
  }
  setOnBase(value: boolean): void {
    this._onBase = value;
  }
  setOnHead(value: boolean): void {
    this._onHead = value;
  }
  setOrdinal(value: number): void {
    this._ordinal = value;
  }
  setRenderStatus(value: "pending" | "rendered" | "partial" | "failed" | "skipped"): void {
    this._renderStatus = value;
  }
  setStateName(value: string): void {
    this._stateName = value;
  }
  setSteps(value: HarnessStep[]): void {
    this._steps = value;
  }
  setUpdatedAt(value: Date): void {
    this._updatedAt = value;
  }
  setVisualChange(value: "changed" | "unchanged" | "new" | "deleted" | null): void {
    this._visualChange = value;
  }
  setVisualizationComponentId(value: number): void {
    this._visualizationComponentId = value;
  }
  setVisualizationId(value: number): void {
    this._visualizationId = value;
  }

  // ===== Getters =====
  get baseError(): string | null {
    return this._baseError;
  }
  get baseFailureKind():
    | "vite_unavailable"
    | "navigation"
    | "module_load"
    | "render_error"
    | "timeout"
    | "step_failed"
    | "browser"
    | "screenshot"
    | "file_missing"
    | "budget_exceeded"
    | "cancelled"
    | null {
    return this._baseFailureKind;
  }
  get baseImagePath(): string | null {
    return this._baseImagePath;
  }
  get createdAt(): Date {
    return this._createdAt;
  }
  get diffImagePath(): string | null {
    return this._diffImagePath;
  }
  get diffPixelRatio(): number | null {
    return this._diffPixelRatio;
  }
  get headError(): string | null {
    return this._headError;
  }
  get headFailureKind():
    | "vite_unavailable"
    | "navigation"
    | "module_load"
    | "render_error"
    | "timeout"
    | "step_failed"
    | "browser"
    | "screenshot"
    | "file_missing"
    | "budget_exceeded"
    | "cancelled"
    | null {
    return this._headFailureKind;
  }
  get headImagePath(): string | null {
    return this._headImagePath;
  }
  get id(): number {
    return this._id;
  }
  get imageHeight(): number | null {
    return this._imageHeight;
  }
  get imageWidth(): number | null {
    return this._imageWidth;
  }
  get onBase(): boolean {
    return this._onBase;
  }
  get onHead(): boolean {
    return this._onHead;
  }
  get ordinal(): number {
    return this._ordinal;
  }
  get renderStatus(): "pending" | "rendered" | "partial" | "failed" | "skipped" {
    return this._renderStatus;
  }
  get stateName(): string {
    return this._stateName;
  }
  get steps(): HarnessStep[] {
    return this._steps;
  }
  get updatedAt(): Date {
    return this._updatedAt;
  }
  get visualChange(): "changed" | "unchanged" | "new" | "deleted" | null {
    return this._visualChange;
  }
  get visualizationComponentId(): number {
    return this._visualizationComponentId;
  }
  get visualizationId(): number {
    return this._visualizationId;
  }
}
