// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.

/**
 * VisualizationConsoleEventModel
 * Auto-generated from Drizzle schema table "visualization_console_events"
 */
export class VisualizationConsoleEventModel {
  private _createdAt!: Date;
  private _id!: number;
  private _level!: "info" | "warn" | "error";
  private _message!: string;
  private _stage!:
    | "queued"
    | "preparing"
    | "analyzing"
    | "awaiting_confirmation"
    | "generating_harnesses"
    | "rendering"
    | "diffing"
    | "summarizing"
    | "completed"
    | "failed"
    | "cancelled";
  private _visualizationId!: number;

  constructor(data?: Partial<Record<keyof VisualizationConsoleEventModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setLevel(value: "info" | "warn" | "error"): void {
    this._level = value;
  }
  setMessage(value: string): void {
    this._message = value;
  }
  setStage(
    value:
      | "queued"
      | "preparing"
      | "analyzing"
      | "awaiting_confirmation"
      | "generating_harnesses"
      | "rendering"
      | "diffing"
      | "summarizing"
      | "completed"
      | "failed"
      | "cancelled"
  ): void {
    this._stage = value;
  }
  setVisualizationId(value: number): void {
    this._visualizationId = value;
  }

  // ===== Getters =====
  get createdAt(): Date {
    return this._createdAt;
  }
  get id(): number {
    return this._id;
  }
  get level(): "info" | "warn" | "error" {
    return this._level;
  }
  get message(): string {
    return this._message;
  }
  get stage():
    | "queued"
    | "preparing"
    | "analyzing"
    | "awaiting_confirmation"
    | "generating_harnesses"
    | "rendering"
    | "diffing"
    | "summarizing"
    | "completed"
    | "failed"
    | "cancelled" {
    return this._stage;
  }
  get visualizationId(): number {
    return this._visualizationId;
  }
}
