// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.
import type { AiUsage } from "../types/visualization-pipeline";

/**
 * VisualizationModel
 * Auto-generated from Drizzle schema table "visualizations"
 */
export class VisualizationModel {
  private _aiModel!: string;
  private _aiProvider!: "anthropic_api" | "claude_code";
  private _aiUsage!: AiUsage | null;
  private _baseRef!: string;
  private _baseSha!: string | null;
  private _changedCount!: number;
  private _completedAt!: Date | null;
  private _componentCount!: number;
  private _componentLimit!: number | null;
  private _createdAt!: Date;
  private _errorMessage!: string | null;
  private _failedStage!:
    | "queued"
    | "awaiting_confirmation"
    | "preparing"
    | "analyzing"
    | "generating_harnesses"
    | "rendering"
    | "diffing"
    | "summarizing"
    | null;
  private _headRef!: string;
  private _headSha!: string | null;
  private _id!: number;
  private _isDeleted!: boolean;
  private _jobId!: string | null;
  private _prNumber!: number | null;
  private _renderViewport!: "desktop" | "tablet" | "mobile" | null;
  private _repositoryId!: number;
  private _sourceType!: "github_pr" | "local_branch" | "working_tree" | "commit_range";
  private _startedAt!: Date | null;
  private _status!:
    | "queued"
    | "preparing"
    | "analyzing"
    | "awaiting_confirmation"
    | "generating_harnesses"
    | "rendering"
    | "diffing"
    | "summarizing"
    | "completed"
    | "failed"
    | "cancelled";
  private _summaryMarkdown!: string | null;
  private _title!: string;
  private _updatedAt!: Date;

  constructor(data?: Partial<Record<keyof VisualizationModel, unknown>>) {
    if (!data) {
      return;
    }
    for (const [key, value] of Object.entries(data)) {
      if (value === undefined || value === null) {
        continue;
      }
      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;
      const setter = (this as unknown as Record<string, unknown>)[setterName];
      if (typeof setter === "function") {
        (setter as (input: unknown) => void).call(this, value);
      }
    }
  }

  // ===== Setters =====
  setAiModel(value: string): void {
    this._aiModel = value;
  }
  setAiProvider(value: "anthropic_api" | "claude_code"): void {
    this._aiProvider = value;
  }
  setAiUsage(value: AiUsage | null): void {
    this._aiUsage = value;
  }
  setBaseRef(value: string): void {
    this._baseRef = value;
  }
  setBaseSha(value: string | null): void {
    this._baseSha = value;
  }
  setChangedCount(value: number): void {
    this._changedCount = value;
  }
  setCompletedAt(value: Date | null): void {
    this._completedAt = value;
  }
  setComponentCount(value: number): void {
    this._componentCount = value;
  }
  setComponentLimit(value: number | null): void {
    this._componentLimit = value;
  }
  setCreatedAt(value: Date): void {
    this._createdAt = value;
  }
  setErrorMessage(value: string | null): void {
    this._errorMessage = value;
  }
  setFailedStage(
    value:
      | "queued"
      | "awaiting_confirmation"
      | "preparing"
      | "analyzing"
      | "generating_harnesses"
      | "rendering"
      | "diffing"
      | "summarizing"
      | null
  ): void {
    this._failedStage = value;
  }
  setHeadRef(value: string): void {
    this._headRef = value;
  }
  setHeadSha(value: string | null): void {
    this._headSha = value;
  }
  setId(value: number): void {
    this._id = value;
  }
  setIsDeleted(value: boolean): void {
    this._isDeleted = value;
  }
  setJobId(value: string | null): void {
    this._jobId = value;
  }
  setPrNumber(value: number | null): void {
    this._prNumber = value;
  }
  setRenderViewport(value: "desktop" | "tablet" | "mobile" | null): void {
    this._renderViewport = value;
  }
  setRepositoryId(value: number): void {
    this._repositoryId = value;
  }
  setSourceType(value: "github_pr" | "local_branch" | "working_tree" | "commit_range"): void {
    this._sourceType = value;
  }
  setStartedAt(value: Date | null): void {
    this._startedAt = value;
  }
  setStatus(
    value:
      | "queued"
      | "preparing"
      | "analyzing"
      | "awaiting_confirmation"
      | "generating_harnesses"
      | "rendering"
      | "diffing"
      | "summarizing"
      | "completed"
      | "failed"
      | "cancelled"
  ): void {
    this._status = value;
  }
  setSummaryMarkdown(value: string | null): void {
    this._summaryMarkdown = value;
  }
  setTitle(value: string): void {
    this._title = value;
  }
  setUpdatedAt(value: Date): void {
    this._updatedAt = value;
  }

  // ===== Getters =====
  get aiModel(): string {
    return this._aiModel;
  }
  get aiProvider(): "anthropic_api" | "claude_code" {
    return this._aiProvider;
  }
  get aiUsage(): AiUsage | null {
    return this._aiUsage;
  }
  get baseRef(): string {
    return this._baseRef;
  }
  get baseSha(): string | null {
    return this._baseSha;
  }
  get changedCount(): number {
    return this._changedCount;
  }
  get completedAt(): Date | null {
    return this._completedAt;
  }
  get componentCount(): number {
    return this._componentCount;
  }
  get componentLimit(): number | null {
    return this._componentLimit;
  }
  get createdAt(): Date {
    return this._createdAt;
  }
  get errorMessage(): string | null {
    return this._errorMessage;
  }
  get failedStage():
    | "queued"
    | "awaiting_confirmation"
    | "preparing"
    | "analyzing"
    | "generating_harnesses"
    | "rendering"
    | "diffing"
    | "summarizing"
    | null {
    return this._failedStage;
  }
  get headRef(): string {
    return this._headRef;
  }
  get headSha(): string | null {
    return this._headSha;
  }
  get id(): number {
    return this._id;
  }
  get isDeleted(): boolean {
    return this._isDeleted;
  }
  get jobId(): string | null {
    return this._jobId;
  }
  get prNumber(): number | null {
    return this._prNumber;
  }
  get renderViewport(): "desktop" | "tablet" | "mobile" | null {
    return this._renderViewport;
  }
  get repositoryId(): number {
    return this._repositoryId;
  }
  get sourceType(): "github_pr" | "local_branch" | "working_tree" | "commit_range" {
    return this._sourceType;
  }
  get startedAt(): Date | null {
    return this._startedAt;
  }
  get status():
    | "queued"
    | "preparing"
    | "analyzing"
    | "awaiting_confirmation"
    | "generating_harnesses"
    | "rendering"
    | "diffing"
    | "summarizing"
    | "completed"
    | "failed"
    | "cancelled" {
    return this._status;
  }
  get summaryMarkdown(): string | null {
    return this._summaryMarkdown;
  }
  get title(): string {
    return this._title;
  }
  get updatedAt(): Date {
    return this._updatedAt;
  }
}
