/**
 * Generates backend/src/models/* from src/database/schema.ts (03 §9.1).
 *
 * Copied from Uply-v2 backend/scripts/generate-models.ts and adapted: nullable columns are typed `T | null`,
 * jsonb columns take their type from JSON_COLUMN_TYPES (a missing entry is an error), the constructor is
 * lint-clean under strictTypeChecked, and every file is formatted in memory with Prettier so `models:drift`
 * is stable.
 */
import fs from "node:fs";
import path from "node:path";
import { Table as DrizzleTable, getTableColumns, getTableName } from "drizzle-orm";
import * as prettier from "prettier";
import * as schema from "../src/database/schema";

/** The subset of a Drizzle column the generator reads. Exported so tests can pass fake columns. */
export interface ColumnMetadata {
  dataType?: string;
  enumValues?: readonly string[] | undefined;
  notNull?: boolean;
  getSQLType?: () => string;
}

/** One generated field. `tsType` excludes `| null`; `nullable` adds it. */
export interface ColumnDefinition {
  name: string;
  tsType: string;
  nullable: boolean;
  typeImports: string[];
  /** Module `typeImports` come from (relative to src/models); null when there are none. */
  typesModule: string | null;
}

/** One generated model class. */
export interface TableDefinition {
  exportName: string;
  tableName: string;
  className: string;
  columns: ColumnDefinition[];
}

/** TS type of a mapped column plus the type names it needs and the module they come from. */
export interface MappedColumnType {
  tsType: string;
  typeImports: string[];
  /** Module `typeImports` come from (relative to src/models); null when there are none. */
  typesModule: string | null;
}

/** Export name → class name, for tables whose singular form the heuristic gets wrong. Empty for PRVision v1. */
const CLASS_NAME_OVERRIDES: Record<string, string> = {};

/** Modules json column types come from, relative to src/models. */
const PIPELINE_TYPES_MODULE = "../types/visualization-pipeline";
const LIBRARY_TYPES_MODULE = "../types/harness-library";

/**
 * Types of jsonb columns, keyed by `${exportName}.${propertyName}`. Every json column must have an entry:
 * an untyped jsonb column would otherwise become `unknown` and leak casts into services. Each entry names the
 * module its types come from (16 §6.10); the generator emits one `import type` line per module.
 */
export const JSON_COLUMN_TYPES: Record<string, MappedColumnType> = {
  "repositories.globalStylePaths": { tsType: "string[]", typeImports: [], typesModule: null },
  "visualizations.aiUsage": { tsType: "AiUsage", typeImports: ["AiUsage"], typesModule: PIPELINE_TYPES_MODULE },
  "visualizationComponents.mockedModules": {
    tsType: "MockedModule[]",
    typeImports: ["MockedModule"],
    typesModule: PIPELINE_TYPES_MODULE
  },
  "visualizationComponents.structuralDiff": {
    tsType: "StructuralChange[]",
    typeImports: ["StructuralChange"],
    typesModule: PIPELINE_TYPES_MODULE
  },
  "visualizationComponents.baseMockedModules": {
    tsType: "MockedModule[]",
    typeImports: ["MockedModule"],
    typesModule: PIPELINE_TYPES_MODULE
  },
  "visualizationComponents.successorEvidence": {
    tsType: "SuccessorEvidence[]",
    typeImports: ["SuccessorEvidence"],
    typesModule: PIPELINE_TYPES_MODULE
  },
  // ---- 16 §6.10 ----
  "harnessLibraryEntries.mockedModules": {
    tsType: "MockedModule[]",
    typeImports: ["MockedModule"],
    typesModule: PIPELINE_TYPES_MODULE
  },
  "harnessLibraryEntries.states": {
    tsType: "HarnessStateSpec[]",
    typeImports: ["HarnessStateSpec"],
    typesModule: LIBRARY_TYPES_MODULE
  },
  "harnessLibraryEntries.aiUsage": { tsType: "AiUsage", typeImports: ["AiUsage"], typesModule: PIPELINE_TYPES_MODULE },
  "harnessLibraryJobs.componentIds": { tsType: "number[]", typeImports: [], typesModule: null },
  "harnessLibraryJobs.aiUsage": { tsType: "AiUsage", typeImports: ["AiUsage"], typesModule: PIPELINE_TYPES_MODULE },
  "visualizationComponentStates.steps": {
    tsType: "HarnessStep[]",
    typeImports: ["HarnessStep"],
    typesModule: LIBRARY_TYPES_MODULE
  },
  "liveSessions.hosts": {
    tsType: "LiveHostState[]",
    typeImports: ["LiveHostState"],
    typesModule: LIBRARY_TYPES_MODULE
  },
  "liveSessions.openRequests": {
    tsType: "LiveOpenRequestRecord[]",
    typeImports: ["LiveOpenRequestRecord"],
    typesModule: LIBRARY_TYPES_MODULE
  }
};

const HEADER = "// AUTO-GENERATED by scripts/generate-models.ts from src/database/schema.ts — DO NOT EDIT.";

const backendDir = path.resolve(__dirname, "..");
const MODELS_DIR = path.join(backendDir, "src/models");

const DRIZZLE_TABLE_COLUMNS = (DrizzleTable as unknown as { Symbol: { Columns: symbol } }).Symbol.Columns;

function isSchemaTable(value: unknown): value is DrizzleTable {
  return Boolean(
    value && typeof value === "object" && Object.prototype.hasOwnProperty.call(value, DRIZZLE_TABLE_COLUMNS)
  );
}

function toPascalCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function toSingular(exportName: string): string {
  const override = CLASS_NAME_OVERRIDES[exportName];
  if (override) {
    return override.replace(/Model$/, "");
  }

  if (exportName.endsWith("ies")) {
    return toPascalCase(exportName.slice(0, -3) + "y");
  }

  if (exportName.endsWith("s")) {
    return toPascalCase(exportName.slice(0, -1));
  }

  return toPascalCase(exportName);
}

function toKebabCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

function resolveArrayType(sqlType: string): string {
  if (sqlType.startsWith("text[]") || sqlType.startsWith("varchar[]")) {
    return "string[]";
  }

  if (sqlType.startsWith("integer[]") || sqlType.startsWith("numeric[]")) {
    return "number[]";
  }

  if (sqlType.startsWith("boolean[]")) {
    return "boolean[]";
  }

  return "unknown[]";
}

/**
 * Maps a Drizzle column to its TypeScript type (without `| null`).
 *
 * @param exportName - Schema export of the table (e.g. `visualizations`), used for JSON_COLUMN_TYPES lookups.
 * @param propertyName - camelCase property of the column.
 * @param column - The column (or a fake with the same metadata in tests).
 * @throws Error when a json column has no JSON_COLUMN_TYPES entry.
 */
export function mapColumnType(exportName: string, propertyName: string, column: ColumnMetadata): MappedColumnType {
  if (column.dataType === "json") {
    const mapped = JSON_COLUMN_TYPES[`${exportName}.${propertyName}`];
    if (!mapped) {
      throw new Error(`Missing JSON_COLUMN_TYPES entry for ${exportName}.${propertyName}`);
    }
    return { tsType: mapped.tsType, typeImports: [...mapped.typeImports], typesModule: mapped.typesModule };
  }

  if (Array.isArray(column.enumValues) && column.enumValues.length > 0) {
    return {
      tsType: column.enumValues.map((value) => JSON.stringify(value)).join(" | "),
      typeImports: [],
      typesModule: null
    };
  }

  const sqlType = typeof column.getSQLType === "function" ? column.getSQLType() : "";
  if (sqlType.endsWith("[]")) {
    return plainType(resolveArrayType(sqlType));
  }

  switch (column.dataType) {
    case "string":
      return plainType("string");
    case "number":
      return plainType("number");
    case "boolean":
      return plainType("boolean");
    case "date":
      return plainType("Date");
    case "array":
      return plainType("unknown[]");
    default:
      return plainType("unknown");
  }
}

function plainType(tsType: string): MappedColumnType {
  return { tsType, typeImports: [], typesModule: null };
}

/** Reads every table export of schema.ts, sorted by SQL table name; columns sorted by property name. */
export function readSchemaTables(): TableDefinition[] {
  const schemaEntries: Array<[string, unknown]> = Object.entries(schema);

  return schemaEntries
    .filter((entry): entry is [string, DrizzleTable] => isSchemaTable(entry[1]))
    .map(([exportName, table]) => {
      const columns = Object.entries(getTableColumns(table))
        .map(([propertyName, column]): ColumnDefinition => {
          const mapped = mapColumnType(exportName, propertyName, column);
          return {
            name: propertyName,
            tsType: mapped.tsType,
            nullable: !column.notNull,
            typeImports: mapped.typeImports,
            typesModule: mapped.typesModule
          };
        })
        .sort((left, right) => left.name.localeCompare(right.name));

      const className = CLASS_NAME_OVERRIDES[exportName] ?? `${toSingular(exportName)}Model`;
      return {
        exportName,
        tableName: getTableName(table),
        className,
        columns
      };
    })
    .sort((left, right) => left.tableName.localeCompare(right.tableName));
}

function fieldType(column: ColumnDefinition): string {
  return column.nullable ? `${column.tsType} | null` : column.tsType;
}

/** Generates the (unformatted) source of one model class. */
export function generateModelClass(table: TableDefinition): string {
  const lines: string[] = [HEADER];

  const importsByModule = new Map<string, Set<string>>();
  for (const column of table.columns) {
    if (column.typesModule === null || column.typeImports.length === 0) {
      continue;
    }
    const names = importsByModule.get(column.typesModule) ?? new Set<string>();
    column.typeImports.forEach((name) => names.add(name));
    importsByModule.set(column.typesModule, names);
  }
  for (const typesModule of [...importsByModule.keys()].sort()) {
    const names = [...(importsByModule.get(typesModule) ?? [])].sort();
    lines.push(`import type { ${names.join(", ")} } from "${typesModule}";`);
  }
  lines.push("");

  lines.push("/**");
  lines.push(` * ${table.className}`);
  lines.push(` * Auto-generated from Drizzle schema table "${table.tableName}"`);
  lines.push(" */");
  lines.push(`export class ${table.className} {`);

  for (const column of table.columns) {
    lines.push(`  private _${column.name}!: ${fieldType(column)};`);
  }

  lines.push("");
  lines.push(`  constructor(data?: Partial<Record<keyof ${table.className}, unknown>>) {`);
  lines.push("    if (!data) {");
  lines.push("      return;");
  lines.push("    }");
  lines.push("    for (const [key, value] of Object.entries(data)) {");
  lines.push("      if (value === undefined || value === null) {");
  lines.push("        continue;");
  lines.push("      }");
  lines.push("      const setterName = `set${key.charAt(0).toUpperCase()}${key.slice(1)}`;");
  lines.push("      const setter = (this as unknown as Record<string, unknown>)[setterName];");
  lines.push('      if (typeof setter === "function") {');
  lines.push("        (setter as (input: unknown) => void).call(this, value);");
  lines.push("      }");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  // ===== Setters =====");

  for (const column of table.columns) {
    const name = column.name.charAt(0).toUpperCase() + column.name.slice(1);
    lines.push(`  set${name}(value: ${fieldType(column)}): void { this._${column.name} = value; }`);
  }

  lines.push("");
  lines.push("  // ===== Getters =====");

  for (const column of table.columns) {
    lines.push(`  get ${column.name}(): ${fieldType(column)} { return this._${column.name}; }`);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function generateModelIndex(tables: TableDefinition[]): string {
  const exports = tables.map((table) => `export * from "./${toKebabCase(table.className)}";`);
  return [HEADER, "// Run `npm run generate:models` after schema changes.", "", ...exports, ""].join("\n");
}

/** Formats TypeScript source with the backend Prettier config (in memory: src/models is prettier-ignored). */
export async function formatSource(source: string): Promise<string> {
  const prettierOptions = (await prettier.resolveConfig(path.join(backendDir, ".prettierrc.json"))) ?? {};
  return prettier.format(source, { ...prettierOptions, parser: "typescript" });
}

/** Renders every model file and the barrel, formatted. Key = file name inside src/models. */
export async function renderModelFiles(tables: TableDefinition[] = readSchemaTables()): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  for (const table of tables) {
    files.set(`${toKebabCase(table.className)}.ts`, await formatSource(generateModelClass(table)));
  }
  files.set("index.ts", await formatSource(generateModelIndex(tables)));
  return files;
}

function removeGeneratedModels(outputDir: string): void {
  for (const file of fs.readdirSync(outputDir)) {
    if (file.endsWith("-model.ts") || file === "index.ts") {
      fs.unlinkSync(path.join(outputDir, file));
    }
  }
}

async function main(): Promise<void> {
  const tables = readSchemaTables();
  const files = await renderModelFiles(tables);

  fs.mkdirSync(MODELS_DIR, { recursive: true });
  removeGeneratedModels(MODELS_DIR);

  for (const [fileName, content] of files) {
    fs.writeFileSync(path.join(MODELS_DIR, fileName), content, "utf-8");
  }
  for (const table of tables) {
    console.log(`Generated ${table.className} from ${table.exportName}`);
  }
  console.log(`Generated ${tables.length} model classes.`);
}

if (require.main === module) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  });
}
