/**
 * Application, HTTP, data-directory, child-process, git and GitHub configuration.
 *
 * Env-backed values are read here (and in ai.config.ts) and nowhere else (01 §5.10). Reads never throw:
 * a missing required variable is "" and a malformed integer is NaN; validateConfig() (04) reports every
 * problem at boot. Values match 00 §4.
 */
import os from "node:os";
import path from "node:path";
import { optionalEnv, optionalIntegerEnv, pickEnv } from "../utilities/helpers/env";

/**
 * Expands a leading `~` to the user's home directory and resolves to an absolute path.
 *
 * @param value - Raw directory value, e.g. `~/.prvision`.
 * @returns Absolute, normalised path.
 */
export function resolveDataDir(value: string): string {
  const expanded = value === "~" || value.startsWith("~/") ? path.join(os.homedir(), value.slice(1)) : value;
  return path.resolve(expanded);
}

// ---- Process and HTTP (00 §4) ----

/** Product name used in logs and script banners. */
export const APP_NAME = "PRVision";

/** Reported by GET /api/health (00 §14.4). Keep equal to backend/package.json "version". */
export const APP_VERSION = "0.1.0";

/** `NODE_ENV`; default `development`. validateConfig() accepts development | test | production. */
export const NODE_ENV: string = optionalEnv("NODE_ENV") ?? "development";
export const IS_DEVELOPMENT = NODE_ENV === "development";
export const IS_TEST = NODE_ENV === "test";
export const IS_PRODUCTION = NODE_ENV === "production";

/** `PORT`; default `3100`. NaN when malformed (validateConfig reports it). */
export const APP_PORT: number = optionalIntegerEnv("PORT") ?? 3100;

/** `HOST`; default `127.0.0.1` (00 D9). validateConfig() rejects non-loopback values. */
export const APP_HOST: string = optionalEnv("HOST") ?? "127.0.0.1";

/** `FRONTEND_URL`; default `http://localhost:4210`. CORS origin and allowed Origin for writes (00 §14.5). */
export const FRONTEND_URL: string = optionalEnv("FRONTEND_URL") ?? "http://localhost:4210";

/** `LOG_LEVEL`; default `info`, or `silent` under NODE_ENV=test (sheet 14's preload sets `debug`). */
export const LOG_LEVEL: string = optionalEnv("LOG_LEVEL") ?? (IS_TEST ? "silent" : "info");

/** Test-only: mirror the logger's test stream to stdout (`PRVISION_TEST_LOG_STDOUT=1`, sheet 14). */
export const LOG_TEST_STDOUT: boolean = optionalEnv("PRVISION_TEST_LOG_STDOUT") === "1";

/** Prefix of every JSON route (00 §9). */
export const API_PREFIX = "/api";

/** Static artifact mount (00 §9). */
export const ARTIFACTS_ROUTE = "/artifacts";

/** `express.json` body limit. Largest legitimate body is the settings update (two secrets). */
export const JSON_BODY_LIMIT = "1mb";

/** Hard limit for graceful shutdown before `process.exit(1)`. Must exceed WORKER_CLOSE_TIMEOUT_MS. */
export const SHUTDOWN_TIMEOUT_MS = 15_000;

/** Per-check timeout of GET /api/health. */
export const HEALTH_CHECK_TIMEOUT_MS = 2_000;

// ---- Data directory (00 §4) ----

/** `PRVISION_DATA_DIR` with `~` expanded; default `~/.prvision`. */
export const DATA_DIR: string = resolveDataDir(optionalEnv("PRVISION_DATA_DIR") ?? "~/.prvision");

/** `<dataDir>/worktrees/<visualizationId>/{base,head}`. */
export const WORKTREES_DIR_NAME = "worktrees";

/** `<dataDir>/artifacts/<visualizationId>/<componentId>/{base,head,diff}.png`. */
export const ARTIFACTS_DIR_NAME = "artifacts";

/** `<dataDir>/fixtures/sample-react-app`. */
export const FIXTURES_DIR_NAME = "fixtures";
export const FIXTURE_REPO_NAME = "sample-react-app";

// ---- Required secrets and connections (00 §4). "" when unset; validateConfig() fails boot. ----

/** `DATABASE_URL` (required). Never log it: it contains the password. */
export const DATABASE_URL: string = optionalEnv("DATABASE_URL") ?? "";

/** `REDIS_URL` (required). */
export const REDIS_URL: string = optionalEnv("REDIS_URL") ?? "";

/** `PRVISION_SECRET_KEY` (required): base64 of 32 random bytes, generated by `backend/scripts/setup-env.mjs`. */
export const PRVISION_SECRET_KEY: string = optionalEnv("PRVISION_SECRET_KEY") ?? "";

/** Max pg pool connections per process (API and worker each have one pool). */
export const DB_POOL_MAX = 10;

// ---- Child processes (01 §5.9, 00 §14.5) ----

/**
 * The only parent variables a child process (git, Vite host, Claude Code) may inherit. Never contains
 * PRVISION_*, DATABASE_URL, REDIS_URL, NODE_OPTIONS, GIT_* or ANTHROPIC_* (05 adds its own variables for the
 * Claude Code child through AI_CLAUDE_CODE_PARENT_ENV).
 */
export const CHILD_PROCESS_ENV_ALLOWLIST = [
  "PATH",
  "HOME",
  "USER",
  "LOGNAME",
  "SHELL",
  "LANG",
  "LANGUAGE",
  "TZ",
  "TMPDIR",
  "TMP",
  "TEMP",
  "TERM",
  "SSH_AUTH_SOCK",
  "HTTP_PROXY",
  "HTTPS_PROXY",
  "NO_PROXY",
  "http_proxy",
  "https_proxy",
  "no_proxy",
  "NODE_EXTRA_CA_CERTS",
  "SSL_CERT_FILE",
  "SSL_CERT_DIR",
  "XDG_CONFIG_HOME",
  "XDG_CACHE_HOME",
  "XDG_DATA_HOME",
  "XDG_RUNTIME_DIR"
] as const;

/** Variable-name prefixes a child may inherit (locale settings). */
export const CHILD_PROCESS_ENV_ALLOWED_PREFIXES = ["LC_"] as const;

/** Frozen snapshot (taken at import) of the allow-listed parent variables. Base env of every child. */
export const CHILD_PROCESS_BASE_ENV: Readonly<Record<string, string>> = Object.freeze(
  pickEnv(CHILD_PROCESS_ENV_ALLOWLIST, CHILD_PROCESS_ENV_ALLOWED_PREFIXES)
);

/** Default per-stream output cap of `runProcess`. */
export const CHILD_PROCESS_MAX_BUFFER_BYTES = 10 * 1024 * 1024;

/** SIGTERM → SIGKILL grace period when a child is killed (timeout, abort, buffer overflow). */
export const PROCESS_KILL_GRACE_MS = 2_000;

/** Max length of free text in debug logs (01 §5.8). */
export const LOG_TEXT_MAX_LENGTH = 2_000;

// ---- git (04 §9.5) ----

/** git executable, resolved through PATH. */
export const GIT_BINARY = "git";

/** Oldest supported git (00 §14.1): GIT_CONFIG_COUNT env config and --no-write-fetch-head. */
export const GIT_MIN_VERSION = "2.31.0";

/** Timeout of ordinary git commands. */
export const GIT_DEFAULT_TIMEOUT_MS = 30_000;

/** Timeout of `git fetch` (PR heads). */
export const GIT_FETCH_TIMEOUT_MS = 180_000;

/** Timeout of `git worktree add/remove` (checkout of large repos). */
export const GIT_WORKTREE_TIMEOUT_MS = 180_000;

/** Output cap of git commands; also the working-tree patch size limit (07). */
export const GIT_MAX_BUFFER_BYTES = 64 * 1024 * 1024;

/** Namespace for refs PRVision may create in the user's clone (`refs/prvision/pr-<n>`, 00 §4). */
export const GIT_REF_NAMESPACE = "refs/prvision";

// ---- GitHub and project detection (05, 06) ----

export const GITHUB_API_BASE_URL = "https://api.github.com";
export const GITHUB_USER_AGENT = "PRVision/0.1 (local developer tool)";
/** Per-request timeout of GitHub REST calls (06). */
export const GITHUB_REQUEST_TIMEOUT_MS = 15_000;
/** Timeout of POST /api/settings/test-github (05). */
export const GITHUB_TEST_TIMEOUT_MS = 15_000;
/** GitHub's max per_page. */
export const GITHUB_PR_LIST_PAGE_SIZE = 100;
/** At most 300 open PRs are listed. */
export const GITHUB_PR_LIST_MAX_PAGES = 3;
/** Larger files are not read during project detection (06). */
export const DETECTION_MAX_FILE_BYTES = 1_048_576;
/** Oldest Vite major accepted at registration (06; sheet 10 enforces SUPPORTED_VITE_MAJOR_* at render time). */
export const MIN_VITE_MAJOR = 4;
export const MAX_GLOBAL_STYLES = 20;
export const BRANCH_LIST_MAX = 500;
/** GET /api/repositories/:id/commits page size: default and maximum `limit` (00 §16). */
export const COMMIT_LIST_DEFAULT_LIMIT = 50;
export const COMMIT_LIST_MAX_LIMIT = 200;
/** Longest commit search text (GET /api/repositories/:id/commits?q=). */
export const COMMIT_SEARCH_MAX_CHARS = 100;
/** App discovery (15 §5.4.3): at most this many angular.json / vite.config.* files are inspected per repository. */
export const APP_DISCOVERY_MAX_CONFIGS = 50;
