/**
 * Harness workspace (10 §5.4): side layouts, the static templates, `.gitignore`, the generated `globals.ts` and
 * per-component harness modules written into `<viteRoot>/.prvision-harness/`, the rename rewrite of the target
 * import, and the referenced-env-key scan.
 */
import { randomBytes } from "node:crypto";
import type { Dirent } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";
import { HARNESS_DIR_NAME, HARNESS_TEMPLATES_DIR } from "../../../../config-consts";
import { packageNameOf } from "../mock-rules";
import type { HarnessSideLayout, RenderSide } from "./render-types";

export const HARNESS_JSX_PRAGMA = "/** @jsxRuntime automatic */";
export const HARNESS_TEMPLATE_FILES = ["index.html", "entry.tsx", "error-boundary.tsx"] as const;
export const HARNESS_CACHE_DIR_NAME = ".vite-cache";
export const HARNESS_COMPONENTS_DIR_NAME = "components";

function toPosix(value: string): string {
  return value.split(path.sep).join("/");
}

/** Thrown when backend/harness-templates (or one of its three files) is missing. */
export class HarnessTemplatesMissingError extends Error {
  override readonly name = "HarnessTemplatesMissingError";
}

/**
 * Throws Error("Path escapes worktree: …") if `child` is not inside `parent` (or equal to it) after path.resolve.
 *
 * @param parent - Containing directory.
 * @param child - Candidate path.
 */
export function assertInside(parent: string, child: string): void {
  const resolvedParent = path.resolve(parent);
  const resolvedChild = path.resolve(child);
  const relative = path.relative(resolvedParent, resolvedChild);
  if (relative === "") {
    return;
  }
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Path escapes worktree: ${child}`);
  }
}

/**
 * Computes the harness layout of one side. `viteRoot` is the directory of `viteConfigPath` (repo-relative) inside
 * the worktree, or the worktree itself. `configFile` is the absolute config path; the caller sets it to null when
 * the file does not exist on that side.
 *
 * @throws Error("Path escapes worktree: …") when `viteConfigPath` leaves the worktree.
 */
export function resolveSideLayout(
  side: RenderSide,
  worktreeDir: string,
  viteConfigPath: string | null
): HarnessSideLayout {
  const root = path.resolve(worktreeDir);
  let viteRoot = root;
  let configFile: string | null = null;
  if (viteConfigPath !== null && viteConfigPath !== "") {
    configFile = path.resolve(root, viteConfigPath);
    assertInside(root, configFile);
    viteRoot = path.dirname(configFile);
  }
  const harnessDir = path.join(viteRoot, HARNESS_DIR_NAME);
  return {
    side,
    worktreeDir: root,
    viteRoot,
    configFile,
    harnessDir,
    componentsDir: path.join(harnessDir, HARNESS_COMPONENTS_DIR_NAME),
    cacheDir: path.join(harnessDir, HARNESS_CACHE_DIR_NAME),
    harnessUrlPath: `/${toPosix(path.relative(viteRoot, harnessDir))}/index.html`
  };
}

/** Root-relative POSIX path of a file inside the harness dir (for optimizeDeps.entries / warmup). */
export function harnessRootRelative(layout: HarnessSideLayout, ...segments: string[]): string {
  return toPosix(path.relative(layout.viteRoot, path.join(layout.harnessDir, ...segments)));
}

/** Prepends the automatic-runtime pragma unless the harness already declares a JSX pragma. */
export function toHarnessFileSource(harnessSource: string): string {
  const hasPragma = /@jsx(Runtime|ImportSource)?\s/.test(harnessSource.slice(0, 2000));
  const header = `// Generated by PRVision for this render run. Do not edit.\n`;
  return hasPragma ? `${header}${harnessSource}\n` : `${HARNESS_JSX_PRAGMA}\n${header}${harnessSource}\n`;
}

/**
 * Replaces the single module specifier string literal equal to `from` (ImportDeclaration/ExportDeclaration only)
 * by `to`. AST-based (TSX): splices the text inside the quotes.
 *
 * @throws Error("target specifier not found exactly once") when the count is not 1.
 */
export function rewriteTargetSpecifier(source: string, from: string, to: string): string {
  const sourceFile = ts.createSourceFile("harness.tsx", source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const hits: ts.StringLiteral[] = [];
  for (const statement of sourceFile.statements) {
    if (
      (ts.isImportDeclaration(statement) || ts.isExportDeclaration(statement)) &&
      statement.moduleSpecifier !== undefined &&
      ts.isStringLiteral(statement.moduleSpecifier) &&
      statement.moduleSpecifier.text === from
    ) {
      hits.push(statement.moduleSpecifier);
    }
  }
  const hit = hits[0];
  if (hits.length !== 1 || hit === undefined) {
    throw new Error("target specifier not found exactly once");
  }
  const start = hit.getStart(sourceFile) + 1;
  const end = hit.getEnd() - 1;
  return `${source.slice(0, start)}${to}${source.slice(end)}`;
}

/**
 * Builds `globals.ts`: one side-effect import per global style specifier, in detection order. Root-relative
 * repository files (`/src/index.css`) become relative imports from the harness dir; bare package stylesheets are
 * kept when the package is installed. Missing entries are commented out and reported.
 *
 * @throws Error("Path escapes worktree: …") for a root-relative entry that leaves the worktree.
 */
export function buildGlobalsSource(
  layout: HarnessSideLayout,
  globalStylePaths: readonly string[],
  exists: (absolutePath: string) => boolean
): { source: string; missing: string[] } {
  const lines = ["// Generated by PRVision: global styles of the repository, in detection order.", ""];
  const missing: string[] = [];
  for (const specifier of globalStylePaths) {
    if (specifier.startsWith("/")) {
      // "/src/…" is a Vite URL: it is relative to the Vite root (the app folder), not the repository root.
      const absolute = path.join(layout.viteRoot, specifier.slice(1));
      assertInside(layout.worktreeDir, absolute);
      if (!exists(absolute)) {
        missing.push(specifier);
        lines.push(`// missing on the ${layout.side} side: ${specifier}`);
        continue;
      }
      const relative = toPosix(path.relative(layout.harnessDir, absolute));
      lines.push(`import ${JSON.stringify(relative.startsWith(".") ? relative : `./${relative}`)};`);
      continue;
    }
    // Bare package stylesheet: emit only when the package is installed (a failing import would break every render).
    const pkg = packageNameOf(specifier);
    if (pkg === null || !exists(path.join(layout.viteRoot, "node_modules", pkg, "package.json"))) {
      missing.push(specifier);
      lines.push(`// package not installed: ${specifier}`);
      continue;
    }
    lines.push(`import ${JSON.stringify(specifier)};`);
  }
  lines.push("", "export {};", "");
  return { source: lines.join("\n"), missing };
}

async function writeAtomic(target: string, content: string): Promise<void> {
  const temp = `${target}.${randomBytes(4).toString("hex")}.tmp`;
  try {
    await fs.writeFile(temp, content, "utf8");
    await fs.rename(temp, target);
  } catch (error) {
    await fs.rm(temp, { force: true });
    throw error;
  }
}

async function pathExists(absolutePath: string): Promise<boolean> {
  try {
    await fs.access(absolutePath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Throws HarnessTemplatesMissingError when index.html, entry.tsx or error-boundary.tsx is absent in `dir`.
 *
 * @param dir - The templates directory (HARNESS_TEMPLATES_DIR).
 */
export async function assertTemplatesPresent(dir: string): Promise<void> {
  for (const file of HARNESS_TEMPLATE_FILES) {
    if (!(await pathExists(path.join(dir, file)))) {
      throw new HarnessTemplatesMissingError(
        "PRVision's harness templates are missing (backend/harness-templates). Reinstall PRVision."
      );
    }
  }
}

/** Writes the harness folder of each side: templates, `.gitignore`, `globals.ts` and component modules. */
export class HarnessWorkspaceWriter {
  constructor(readonly templatesDir: string = HARNESS_TEMPLATES_DIR) {}

  /**
   * mkdir -p, copy templates (overwrite), write .gitignore and globals.ts. Never touches node_modules.
   *
   * @param layout - The side layout.
   * @param globalStylePaths - Repository global style specifiers (00 §14.3).
   * @returns Global style entries that do not exist on this side.
   */
  async prepareSide(
    layout: HarnessSideLayout,
    globalStylePaths: readonly string[]
  ): Promise<{ missingStyles: string[] }> {
    assertInside(layout.worktreeDir, layout.harnessDir);
    assertInside(layout.worktreeDir, layout.componentsDir);
    await fs.mkdir(layout.componentsDir, { recursive: true });
    for (const file of HARNESS_TEMPLATE_FILES) {
      await fs.copyFile(path.join(this.templatesDir, file), path.join(layout.harnessDir, file));
    }
    await writeAtomic(path.join(layout.harnessDir, ".gitignore"), "*\n");
    const probes = new Map<string, boolean>();
    for (const specifier of globalStylePaths) {
      const candidates = specifier.startsWith("/")
        ? [path.join(layout.viteRoot, specifier.slice(1))]
        : [path.join(layout.viteRoot, "node_modules", packageNameOf(specifier) ?? "", "package.json")];
      for (const candidate of candidates) {
        if (isInsideOrEqual(layout.worktreeDir, candidate)) {
          probes.set(candidate, await pathExists(candidate));
        }
      }
    }
    const { source, missing } = buildGlobalsSource(
      layout,
      globalStylePaths,
      (absolute) => probes.get(absolute) ?? false
    );
    await writeAtomic(path.join(layout.harnessDir, "globals.ts"), source);
    return { missingStyles: missing };
  }

  /**
   * Writes components/<id>.tsx atomically (tmp + rename), overwriting an earlier version (repair).
   *
   * @returns The absolute path of the written file.
   */
  async writeComponentHarness(layout: HarnessSideLayout, componentId: number, harnessSource: string): Promise<string> {
    if (!Number.isInteger(componentId) || componentId <= 0) {
      throw new Error(`Invalid component id ${String(componentId)}`);
    }
    const target = path.join(layout.componentsDir, `${String(componentId)}.tsx`);
    assertInside(layout.worktreeDir, target);
    await fs.mkdir(layout.componentsDir, { recursive: true });
    await writeAtomic(target, toHarnessFileSource(harnessSource));
    return target;
  }
}

function isInsideOrEqual(parent: string, child: string): boolean {
  try {
    assertInside(parent, child);
    return true;
  } catch {
    return false;
  }
}

const ENV_SCAN_SKIP_DIRS: ReadonlySet<string> = new Set([
  "node_modules",
  ".git",
  HARNESS_DIR_NAME,
  "dist",
  "build",
  "coverage"
]);
const ENV_SCAN_EXTENSIONS: ReadonlySet<string> = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".mts"]);
const ENV_SCAN_MAX_FILE_BYTES = 1024 * 1024;
const ENV_SCAN_MAX_FILES = 5_000;
const ENV_PREFIX = "VITE_";

/**
 * Collects `import.meta.env.VITE_*` keys referenced in the sources under `roots` (10 §5.4.8), skipping
 * node_modules, .git, the harness dir, dist, build and coverage. Files up to 1 MB, 5 000 files in total.
 *
 * @returns Sorted, de-duplicated key names.
 */
export async function scanReferencedEnvKeys(roots: string[]): Promise<string[]> {
  const keys = new Set<string>();
  let files = 0;
  const pending = [...new Set(roots.map((root) => path.resolve(root)))];
  while (pending.length > 0 && files < ENV_SCAN_MAX_FILES) {
    const dir = pending.shift();
    if (dir === undefined) {
      break;
    }
    let entries: Dirent[];
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    entries.sort((a, b) => a.name.localeCompare(b.name));
    for (const entry of entries) {
      if (files >= ENV_SCAN_MAX_FILES) {
        break;
      }
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!ENV_SCAN_SKIP_DIRS.has(entry.name)) {
          pending.push(full);
        }
        continue;
      }
      if (!entry.isFile() || !ENV_SCAN_EXTENSIONS.has(path.extname(entry.name))) {
        continue;
      }
      files += 1;
      try {
        const stat = await fs.stat(full);
        if (stat.size > ENV_SCAN_MAX_FILE_BYTES) {
          continue;
        }
        const text = await fs.readFile(full, "utf8");
        for (const match of text.matchAll(/import\.meta\.env\.([A-Z][A-Z0-9_]*)/g)) {
          const key = match[1];
          if (key?.startsWith(ENV_PREFIX)) {
            keys.add(key);
          }
        }
      } catch {
        // Unreadable file: skip.
      }
    }
  }
  return [...keys].sort();
}
