/**
 * Angular harness workspace (15 §5.7.5): side layouts and the files written into
 * `<worktree>/<appRoot>/.prvision-harness/`: the static templates, `.gitignore`, the generated `index.html`,
 * `tsconfig.json`, `framework.generated.ts` and `registry.generated.ts`, harness modules and mock files.
 * Never writes outside the harness folder and never touches node_modules or tracked files.
 */
import { randomBytes } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";
import { ANGULAR_HARNESS_TEMPLATES_DIR, HARNESS_DIR_NAME } from "../../../../../config-consts";
import { isPathInside } from "../../../../../utilities";
import { SHARED_TEMPLATE_DIR_NAME, SHARED_TEMPLATE_FILES } from "../harness-workspace";
import { isRecord, type RenderSide } from "../render-types";
import { indexInputOf, usesZone, type AngularProjectInfo, mergedTargetOptions } from "./angular-build-options";

export const ANGULAR_TEMPLATE_FILES = ["main.ts", "harness-api.ts", "http-backend.ts"] as const;
export const ANGULAR_GENERATED_HEADER = "// @ts-nocheck\n// Generated by PRVision for this render run. Do not edit.\n";
const INDEX_MAX_BYTES = 512 * 1024;
const TSCONFIG_MAX_BYTES = 1024 * 1024;
const EXTENDS_MAX_DEPTH = 10;

export interface AngularSideLayout {
  side: RenderSide;
  worktreeDir: string; // absolute
  workspaceRoot: string; // <worktree>/<appRoot> (holds angular.json); the build child's cwd
  harnessDir: string; // <workspaceRoot>/.prvision-harness
  componentsDir: string;
  mocksDir: string;
  distDir: string;
}

function toPosix(value: string): string {
  return value.split(path.sep).join("/");
}

/** Thrown when backend/harness-templates/angular (or one of its files) is missing. */
export class AngularTemplatesMissingError extends Error {
  override readonly name = "AngularTemplatesMissingError";
}

/**
 * Throws Error("Path escapes worktree: …") unless `child` is `parent` or inside it (after path.resolve). Same rule
 * as 10's guard; kept here because Angular code does not import the React harness workspace module (15 §5.3).
 */
export function assertAngularPathInside(parent: string, child: string): void {
  const relative = path.relative(path.resolve(parent), path.resolve(child));
  if (relative !== "" && (relative.startsWith("..") || path.isAbsolute(relative))) {
    throw new Error(`Path escapes worktree: ${child}`);
  }
}

/**
 * Replaces the single import/export module specifier equal to `from` by `to` (TypeScript AST, decorators allowed).
 * Used for the base side of a renamed component.
 *
 * @throws Error("target specifier not found exactly once") when the count is not 1.
 */
export function rewriteAngularTargetSpecifier(source: string, from: string, to: string): string {
  const sourceFile = ts.createSourceFile("harness.ts", source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const hits: ts.StringLiteral[] = [];
  for (const statement of sourceFile.statements) {
    if (
      (ts.isImportDeclaration(statement) || ts.isExportDeclaration(statement)) &&
      statement.moduleSpecifier !== undefined &&
      ts.isStringLiteral(statement.moduleSpecifier) &&
      statement.moduleSpecifier.text === from
    ) {
      hits.push(statement.moduleSpecifier);
    }
  }
  const hit = hits[0];
  if (hits.length !== 1 || hit === undefined) {
    throw new Error("target specifier not found exactly once");
  }
  return `${source.slice(0, hit.getStart(sourceFile) + 1)}${to}${source.slice(hit.getEnd() - 1)}`;
}

/**
 * Computes the harness layout of one side.
 *
 * @throws Error("Path escapes worktree: …") when `appRoot` leaves the worktree.
 */
export function resolveAngularLayout(side: RenderSide, worktreeDir: string, appRoot: string): AngularSideLayout {
  const root = path.resolve(worktreeDir);
  const workspaceRoot = path.resolve(root, appRoot === "" ? "." : appRoot);
  assertAngularPathInside(root, workspaceRoot);
  const harnessDir = path.join(workspaceRoot, HARNESS_DIR_NAME);
  const layout: AngularSideLayout = {
    side,
    worktreeDir: root,
    workspaceRoot,
    harnessDir,
    componentsDir: path.join(harnessDir, "components"),
    mocksDir: path.join(harnessDir, "mocks"),
    distDir: path.join(harnessDir, "dist")
  };
  for (const dir of [layout.harnessDir, layout.componentsDir, layout.mocksDir, layout.distDir]) {
    assertAngularPathInside(root, dir);
  }
  return layout;
}

// ---------------------------------------------------------------------------------------------------------------
// Pure generators
// ---------------------------------------------------------------------------------------------------------------

const BASE_STYLE = `  <style id="prvision-base-style">
    html, body { margin: 0; padding: 0; background: #ffffff; }
    #prvision-root { display: flow-root; box-sizing: border-box; width: 100%; min-height: 48px; padding: 0; }
  </style>`;

const MINIMAL_HEAD = `
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">`;

/**
 * Harness index.html (15 §5.7.5): the app index's `<head>` children with the title replaced, `<base>` dropped and
 * `<base href="/">` inserted, plus the base style block; the body is only `<prvision-root>`.
 *
 * @param appIndexHtml - The build target's index.html, or null when missing (minimal head).
 */
export function buildHarnessIndexHtml(appIndexHtml: string | null): string {
  const head = appIndexHtml === null ? MINIMAL_HEAD : (/<head[^>]*>([\s\S]*?)<\/head>/i.exec(appIndexHtml)?.[1] ?? "");
  const withoutBase = head.replace(/<base\b[^>]*>/gi, "");
  const titled = /<title\b[^>]*>[\s\S]*?<\/title>/i.test(withoutBase)
    ? withoutBase.replace(/<title\b[^>]*>[\s\S]*?<\/title>/i, "<title>PRVision harness</title>")
    : `${withoutBase}\n  <title>PRVision harness</title>`;
  const charset = /<meta\s+charset[^>]*>/i.exec(titled);
  const withBase =
    charset === null
      ? `\n  <base href="/">${titled}`
      : `${titled.slice(0, charset.index + charset[0].length)}\n  <base href="/">${titled.slice(
          charset.index + charset[0].length
        )}`;
  return `<!doctype html>
<html lang="en">
<head>${withBase.trimEnd()}
${BASE_STYLE}
</head>
<body>
  <prvision-root id="prvision-root"></prvision-root>
</body>
</html>
`;
}

/**
 * Harness tsconfig.json (15 §5.7.5): extends the build target's tsconfig, compiles only the harness import graph
 * (`files: ["./main.ts"]`) and keeps ambient `.d.ts` includes rebased to the harness folder.
 *
 * @param harnessDir - Absolute harness dir.
 * @param targetTsconfig - Absolute path of the build target's tsConfig.
 * @param dtsIncludes - Absolute (glob) paths of the effective `.d.ts` include entries.
 */
export function buildHarnessTsconfig(
  harnessDir: string,
  targetTsconfig: string,
  dtsIncludes: readonly string[]
): string {
  const relative = (target: string): string => {
    const rel = toPosix(path.relative(harnessDir, target));
    return rel.startsWith(".") ? rel : `./${rel}`;
  };
  return `${JSON.stringify(
    {
      extends: relative(targetTsconfig),
      compilerOptions: { outDir: "./out-tsc", noUnusedLocals: false, noUnusedParameters: false },
      files: ["./main.ts"],
      include: dtsIncludes.map(relative)
    },
    null,
    2
  )}\n`;
}

export interface FrameworkSourceInput {
  zone: boolean;
  /** Installed @angular/core major, or null when unknown (treated as the newest supported). */
  angularMajor: number | null;
  animations: boolean;
}

/**
 * framework.generated.ts (15 §5.7.5, §5.7.2 notes): zone or zoneless change detection, noop animations when
 * installed, and `FRAMEWORK_WHEN_STABLE` (whenStable on ≥ 18, the isStable observable on 17).
 *
 * @returns The source and a warning when zoneless was requested on Angular 17.
 */
export function buildFrameworkSource(input: FrameworkSourceInput): { source: string; warning: string | null } {
  const major = input.angularMajor ?? Number.MAX_SAFE_INTEGER;
  let detection = "provideZoneChangeDetection";
  let warning: string | null = null;
  if (!input.zone) {
    if (major >= 20) {
      detection = "provideZonelessChangeDetection";
    } else if (major >= 18) {
      detection = "provideExperimentalZonelessChangeDetection";
    } else {
      warning = "Zoneless change detection needs Angular 18 or newer; rendering with zone change detection.";
    }
  }
  const legacyStable = major < 18;
  const lines = [
    "// Generated by PRVision. Do not edit.",
    `import { ${detection}, type ApplicationRef, type EnvironmentProviders, type Provider } from '@angular/core';`
  ];
  if (input.animations) {
    lines.push("import { provideNoopAnimations } from '@angular/platform-browser/animations';");
  }
  if (legacyStable) {
    lines.push("import { firstValueFrom } from 'rxjs';", "import { filter } from 'rxjs/operators';");
  }
  lines.push(
    "",
    "export const FRAMEWORK_PROVIDERS: Array<Provider | EnvironmentProviders> = [",
    `  ${detection}(),`,
    ...(input.animations ? ["  provideNoopAnimations(),"] : []),
    "];",
    "",
    legacyStable
      ? "export const FRAMEWORK_WHEN_STABLE = (appRef: ApplicationRef): Promise<unknown> =>\n  firstValueFrom(appRef.isStable.pipe(filter(Boolean)));"
      : "export const FRAMEWORK_WHEN_STABLE = (appRef: ApplicationRef): Promise<unknown> => appRef.whenStable();",
    ""
  );
  return { source: lines.join("\n"), warning };
}

/** registry.generated.ts: lazy loaders for the harnesses of one build only. */
export function buildRegistrySource(componentIds: readonly number[]): string {
  const lines = [
    "// Generated by PRVision. Do not edit.",
    "export const HARNESS_LOADERS: Record<string, () => Promise<unknown>> = {"
  ];
  for (const id of [...componentIds].sort((a, b) => a - b)) {
    lines.push(`  '${String(id)}': () => import('./components/${String(id)}'),`);
  }
  lines.push("};", "");
  return lines.join("\n");
}

/** Harness or mock file content: `// @ts-nocheck` and the generated-by header, then the source. */
export function toAngularHarnessFileSource(source: string): string {
  return `${ANGULAR_GENERATED_HEADER}${source.endsWith("\n") ? source : `${source}\n`}`;
}

// ---------------------------------------------------------------------------------------------------------------
// tsconfig chain
// ---------------------------------------------------------------------------------------------------------------

interface ParsedTsconfig {
  include: string[] | null;
  extendsList: string[];
}

async function readTsconfig(file: string): Promise<ParsedTsconfig | null> {
  try {
    const stat = await fs.stat(file);
    if (!stat.isFile() || stat.size > TSCONFIG_MAX_BYTES) {
      return null;
    }
    const parsed = ts.parseConfigFileTextToJson(file, await fs.readFile(file, "utf8"));
    if (parsed.error !== undefined || !isRecord(parsed.config)) {
      return null;
    }
    const config = parsed.config;
    const include = Array.isArray(config.include)
      ? config.include.filter((entry): entry is string => typeof entry === "string")
      : null;
    const rawExtends: unknown = config.extends;
    const extendsList =
      typeof rawExtends === "string"
        ? [rawExtends]
        : Array.isArray(rawExtends)
          ? rawExtends.filter((entry): entry is string => typeof entry === "string")
          : [];
    return { include, extendsList };
  } catch {
    return null;
  }
}

function resolveExtends(fromFile: string, specifier: string): string | null {
  const dir = path.dirname(fromFile);
  if (specifier.startsWith(".") || path.isAbsolute(specifier)) {
    const target = path.resolve(dir, specifier);
    return target.endsWith(".json") ? target : `${target}.json`;
  }
  try {
    return require.resolve(specifier, { paths: [dir] });
  } catch {
    return null;
  }
}

/**
 * The `.d.ts` entries of the effective `include` of a tsconfig chain (the nearest config that declares `include`,
 * TypeScript semantics), as absolute glob paths.
 */
export async function effectiveDtsIncludes(tsconfigFile: string, depth = 0): Promise<string[]> {
  if (depth > EXTENDS_MAX_DEPTH) {
    return [];
  }
  const parsed = await readTsconfig(tsconfigFile);
  if (parsed === null) {
    return [];
  }
  if (parsed.include !== null) {
    return parsed.include
      .filter((entry) => entry.endsWith(".d.ts"))
      .map((entry) => path.resolve(path.dirname(tsconfigFile), entry));
  }
  for (const specifier of [...parsed.extendsList].reverse()) {
    const target = resolveExtends(tsconfigFile, specifier);
    if (target === null) {
      continue;
    }
    const found = await readTsconfig(target);
    if (found === null) {
      continue;
    }
    const nested = await effectiveDtsIncludes(target, depth + 1);
    if (nested.length > 0 || found.include !== null) {
      return nested;
    }
  }
  return [];
}

/** Every tsconfig file of the chain (workspace-relative, for side-wide error attribution). */
export async function tsconfigChain(tsconfigFile: string, depth = 0): Promise<string[]> {
  if (depth > EXTENDS_MAX_DEPTH) {
    return [];
  }
  const parsed = await readTsconfig(tsconfigFile);
  if (parsed === null) {
    return [];
  }
  const chain = [tsconfigFile];
  for (const specifier of parsed.extendsList) {
    const target = resolveExtends(tsconfigFile, specifier);
    if (target !== null) {
      chain.push(...(await tsconfigChain(target, depth + 1)));
    }
  }
  return chain;
}

// ---------------------------------------------------------------------------------------------------------------
// Writer
// ---------------------------------------------------------------------------------------------------------------

async function writeAtomic(target: string, content: string): Promise<void> {
  const temp = `${target}.${randomBytes(4).toString("hex")}.tmp`;
  try {
    await fs.writeFile(temp, content, "utf8");
    await fs.rename(temp, target);
  } catch (error) {
    await fs.rm(temp, { force: true });
    throw error;
  }
}

/** Text of a file inside `root` (realpath-confined, at most `maxBytes`), or null. */
export async function readAngularConfinedText(root: string, file: string, maxBytes: number): Promise<string | null> {
  try {
    const [realRoot, realFile] = await Promise.all([fs.realpath(root), fs.realpath(file)]);
    if (!isPathInside(realRoot, realFile)) {
      return null;
    }
    const stat = await fs.stat(realFile);
    if (!stat.isFile() || stat.size > maxBytes) {
      return null;
    }
    return await fs.readFile(realFile, "utf8");
  } catch {
    return null;
  }
}

/** Installed major of a package as resolved from `fromDir` (follows the node_modules links), or null. */
export async function installedPackageMajor(fromDir: string, packageName: string): Promise<number | null> {
  try {
    const manifest = require.resolve(`${packageName}/package.json`, { paths: [fromDir] });
    const parsed: unknown = JSON.parse(await fs.readFile(manifest, "utf8"));
    const version = isRecord(parsed) && typeof parsed.version === "string" ? parsed.version : "";
    const major = Number.parseInt(version.split(".")[0] ?? "", 10);
    return Number.isFinite(major) ? major : null;
  } catch {
    return null;
  }
}

/**
 * Throws AngularTemplatesMissingError when one of the Angular templates is absent in `dir`.
 *
 * @param dir - The Angular templates directory (ANGULAR_HARNESS_TEMPLATES_DIR).
 */
export async function assertAngularTemplatesPresent(dir: string): Promise<void> {
  const files = [
    ...ANGULAR_TEMPLATE_FILES,
    ...SHARED_TEMPLATE_FILES.map((file) => path.join("..", SHARED_TEMPLATE_DIR_NAME, file))
  ];
  for (const file of files) {
    try {
      await fs.access(path.join(dir, file));
    } catch {
      throw new AngularTemplatesMissingError(
        "PRVision's Angular harness templates are missing (backend/harness-templates/angular). Reinstall PRVision."
      );
    }
  }
}

export interface AngularPrepareResult {
  warnings: string[];
  angularMajor: number | null;
  zone: boolean;
  animations: boolean;
  /** Workspace-relative tsconfig chain files (side-wide attribution). */
  tsconfigFiles: string[];
}

/** Writes the Angular harness folder of each side. */
export class AngularHarnessWorkspaceWriter {
  constructor(readonly templatesDir: string = ANGULAR_HARNESS_TEMPLATES_DIR) {}

  /**
   * mkdir -p, copy templates (overwrite), write `.gitignore`, `index.html`, `tsconfig.json` and
   * `framework.generated.ts`, and an empty registry.
   *
   * @param layout - The side layout.
   * @param project - The side's angular.json project.
   * @param configuration - Build configuration (index, tsConfig and polyfills are read from the merged options).
   */
  async prepareSide(
    layout: AngularSideLayout,
    project: AngularProjectInfo,
    configuration: string | null
  ): Promise<AngularPrepareResult> {
    const warnings: string[] = [];
    for (const dir of [layout.componentsDir, layout.mocksDir]) {
      assertAngularPathInside(layout.worktreeDir, dir);
      await fs.mkdir(dir, { recursive: true });
    }
    for (const file of ANGULAR_TEMPLATE_FILES) {
      await fs.copyFile(path.join(this.templatesDir, file), path.join(layout.harnessDir, file));
    }
    // 16 §7.5: the shared step runtime lives next to the React templates (<templates>/shared/).
    for (const file of SHARED_TEMPLATE_FILES) {
      await fs.copyFile(
        path.join(this.templatesDir, "..", SHARED_TEMPLATE_DIR_NAME, file),
        path.join(layout.harnessDir, file)
      );
    }
    await writeAtomic(path.join(layout.harnessDir, ".gitignore"), "*\n");

    const options = mergedTargetOptions(project.build, configuration);
    const indexInput = indexInputOf(options);
    let appIndex: string | null = null;
    if (indexInput !== null) {
      const indexFile = path.resolve(layout.workspaceRoot, indexInput);
      appIndex = isPathInside(layout.worktreeDir, indexFile)
        ? await readAngularConfinedText(layout.worktreeDir, indexFile, INDEX_MAX_BYTES)
        : null;
    }
    if (appIndex === null) {
      warnings.push(
        `The app's index.html could not be read on the ${layout.side} side; the harness page uses a minimal head.`
      );
    }
    await writeAtomic(path.join(layout.harnessDir, "index.html"), buildHarnessIndexHtml(appIndex));

    const tsConfigOption = typeof options.tsConfig === "string" ? options.tsConfig : "tsconfig.json";
    const targetTsconfig = path.resolve(layout.workspaceRoot, tsConfigOption);
    assertAngularPathInside(layout.worktreeDir, targetTsconfig);
    const dtsIncludes = (await effectiveDtsIncludes(targetTsconfig)).filter((entry) =>
      isPathInside(layout.worktreeDir, entry.replace(/\*.*$/, "") || layout.worktreeDir)
    );
    await writeAtomic(
      path.join(layout.harnessDir, "tsconfig.json"),
      buildHarnessTsconfig(layout.harnessDir, targetTsconfig, dtsIncludes)
    );
    const tsconfigFiles = (await tsconfigChain(targetTsconfig))
      .filter((file) => isPathInside(layout.workspaceRoot, file))
      .map((file) => toPosix(path.relative(layout.workspaceRoot, file)));

    const zone = usesZone(options);
    const angularMajor = await installedPackageMajor(layout.workspaceRoot, "@angular/core");
    const animations = (await installedPackageMajor(layout.workspaceRoot, "@angular/animations")) !== null;
    const framework = buildFrameworkSource({ zone, angularMajor, animations });
    if (framework.warning !== null) {
      warnings.push(framework.warning);
    }
    await writeAtomic(path.join(layout.harnessDir, "framework.generated.ts"), framework.source);
    await this.writeRegistry(layout, []);
    return { warnings, angularMajor, zone, animations, tsconfigFiles };
  }

  /** Writes components/<id>.ts (overwrites an earlier version, e.g. after repair). */
  async writeComponentHarness(layout: AngularSideLayout, componentId: number, harnessSource: string): Promise<string> {
    if (!Number.isInteger(componentId) || componentId <= 0) {
      throw new Error(`Invalid component id ${String(componentId)}`);
    }
    const target = path.join(layout.componentsDir, `${String(componentId)}.ts`);
    assertAngularPathInside(layout.harnessDir, target);
    await fs.mkdir(layout.componentsDir, { recursive: true });
    await writeAtomic(target, toAngularHarnessFileSource(harnessSource));
    return target;
  }

  /** Writes mocks/<hash>.ts. */
  async writeMock(layout: AngularSideLayout, hash: string, source: string): Promise<string> {
    if (!/^[0-9a-f]{8,64}$/.test(hash)) {
      throw new Error(`Invalid mock hash ${hash}`);
    }
    const target = path.join(layout.mocksDir, `${hash}.ts`);
    assertAngularPathInside(layout.harnessDir, target);
    await fs.mkdir(layout.mocksDir, { recursive: true });
    await writeAtomic(target, toAngularHarnessFileSource(source));
    return target;
  }

  /** Writes registry.generated.ts for the items of one build. */
  async writeRegistry(layout: AngularSideLayout, componentIds: readonly number[]): Promise<void> {
    await writeAtomic(path.join(layout.harnessDir, "registry.generated.ts"), buildRegistrySource(componentIds));
  }
}
